# Generated by Django 5.1.5 on 2025-01-23 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_price_ticketcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'verbose_name': 'User Tickets Category', 'verbose_name_plural': 'User Tickets Categories'},
        ),
        migrations.AlterModelTable(
            name='ticketcategory',
            table='events_Tickets_categories',
        ),
    ]
