# Generated by Django 5.1.5 on 2025-01-23 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_ticketcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'verbose_name': 'Ticket Category', 'verbose_name_plural': 'Ticket Categories'},
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='sold_count',
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='galleryimage',
            table='gallery_images',
        ),
        migrations.AlterModelTable(
            name='ticketcategory',
            table='ticket_categories',
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_quantity', models.IntegerField()),
                ('sold_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ticket_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ticketcategory')),
            ],
            options={
                'verbose_name': 'Event Ticket',
                'verbose_name_plural': 'Event Tickets',
                'db_table': 'event_tickets',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_categories',
            field=models.ManyToManyField(related_name='events', through='events.EventTicket', to='events.ticketcategory'),
        ),
    ]
